### ISSUE TITLE
[Table] StyleProvider and Aggregation still results in NPE under Jmix 1.3.3

### ISSUE THREAD

**Issue by ValentinBaier** [jmix-framework/jmix#1071]
My colleague @dominikblei reported the following [bug report](https://github.com/jmix-framework/jmix/issues/874) in June.

Since we upgraded our Jmix project to version 1.3.3, we expected this bug to be resolved.

Unfortunately grouping a table still results in a NPE.

Looking at `JmixGroupTable.java:461` the second argument `itemId` is still a hard-coded `null`.
```
if (getCellStyleGenerator() != null) {
    String cellStyle = getCellStyleGenerator().getStyle(this, null, columnId);
    if (cellStyle != null && !cellStyle.isEmpty()) {
        target.addAttribute("style-" + _columnIdMap().key(columnId), cellStyle + "-ag");
    }
}
```

**Comment by Flaurite** [comment]
@ValentinBaier Hello!

The reason of null argument `itemId` is that aggregation row does not belong to an entity instance. I've tried to reproduce the problem following steps @dominikblei provided but with no luck (Jmix v1.3.3).

Could you make sure that method `AbstractTable#getGeneratedCellStyle()` contains null check for itemId? If so, could you please provide a small demo project where the problem is reprodced?
