### ISSUE TITLE
SQLSyntaxErrorException occurs when trying to run Project with Oracle + addon BPM 

### ISSUE THREAD

**Issue by MaxKatyshev** [jmix-framework/jmix#1139]
**Environment**
- Jmix version: 1.3.5 and 1.4.999-SNAPSHOT
- Jmix Studio plugin version: 1.5.SNAPSHOT4737-222
- IntelliJ version: IntelliJ IDEA 2022.2.3 (Ultimate Edition)
- Database: Oracle
- Operating system: Windows

**Steps:**

1. Create new project
2. Change database type to Oracle (please use Oracle server mentioned here: https://youtrack.haulmont.com/articles/PLAT-A-27/Database-servers#Oracle-server-native)
3. Recreate database using studio action
4. Add BPM addon from Marketplace
5. Update database using studio action (update will be successful)
6. Run the project

**ER:** The project started successfully
**AR:**
```
java.sql.SQLSyntaxErrorException: ORA-00942:
```
[log.txt](https://github.com/jmix-framework/jmix/files/9867311/log.txt)

**Comment by gorbunkov** [comment]
The problem is in fact that the database already contains multiple users where Flowable tables exist.
On application startup Flowable engine checks whether the `ACT_GE_PROPERTY` table exists. Under the hood it is done using the code:

```java
tables = databaseMetaData.getTables(catalog, schema, tableName, JDBC_METADATA_TABLE_TYPES);
```

The problem is that `schema` there is empty, so we the code searches for the table not considering the oracle user we've specified in database connection string.

The workaround is to explicitly set the schema name for Flowable. e.g. by providing a process engine configurer bean in the project:

```java
import org.flowable.spring.SpringProcessEngineConfiguration;
import org.flowable.spring.boot.EngineConfigurationConfigurer;
import org.springframework.stereotype.Component;

@Component
public class MyProcessEngineConfigurer implements EngineConfigurationConfigurer<SpringProcessEngineConfiguration> {
    @Override
    public void configure(SpringProcessEngineConfiguration engineConfiguration) {
        //mg1 is the current oracle user
        engineConfiguration.setDatabaseSchema("mg1");
    }
}
```

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4794-222
IntelliJ version: IntelliJ IDEA 2022.2.3 (Community Edition)

To QA:  set the application property: `flowable.database-schema=mg1` where write you database user instesad `mg1`
