### ISSUE TITLE
Association entity is committed along with an entity that references on it

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1184]
Demo project: [composition-bug.zip](https://github.com/jmix-framework/jmix/files/9969134/composition-bug.zip)

* **Project** o-t-m composition to **Task**
* **Project** o-t-m association to **Person**

**Case 1:**

1. Create a new **Project**
2. Create a new **Task (nested)**
3. Commit Task
4. Commit Project

AR: OK. Task will be saved along with parent Project

**Case 2:** 

1. Create a new **Project**
2. Create a new **Participant (nested)**
3. Commit Person

AR:
Exception that referenced entity doesn't exist

AR:
Either referenced entity is committed if all required attributes was set or exception that some required attributes of referenced entity is not set. 

**Note** that the Project Editor still thinks that woks with a new entity and will try to commit Project

**Case 3:**

1. Create a new **Project**
2. Create a new **Task**
3. Commit Task

AR:
Exception that referenced entity doesn't exist

AR:
Either referenced entity is committed if all required attributes was set or exception that some required attributes of referenced entity is not set. 

**Note** that the Project Editor still thinks that woks with a new entity and will try to commit Project

**Case 4:** 

1. Create a new **Project**
2. Create a new **Person**
3. Commit Person

AR:
Exception that referenced entity doesn't exist

AR:
Either referenced entity is committed if all required attributes was set or exception that some required attributes of referenced entity is not set. 

**Note** that the Project Editor still thinks that woks with a new entity and will try to commit Project

**Comment by gorbunkov** [comment]
It's an expected behavior.

When the editor screen is opened not for the composition collection, the new DataContext without parent dataContext is created. The edited entity (e.g. Participant) has a project property filled. When dataContext in Participant editor merges the entity it also merges all its fields (including project). When the participant editor is committed all tracked entities are committed as well. So it's ok that the project is commited here.
