### ISSUE TITLE
FlowUI for Multitenancy add-on

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1207]

**Comment by rusiaikinat** [comment]
For QA
implementation 'io.jmix.multitenancy:jmix-multitenancy-starter'
implementation 'io.jmix.multitenancy:jmix-multitenancy-flowui-starter'

**Comment by rusiaikinat** [comment]
Reopened


1. Allows to create the same tenant
![image](https://user-images.githubusercontent.com/114649487/211288926-ba5b4640-6629-4942-ae7e-2376c29161c1.png)

2.
TC:
Open Tenants > Create tenant1
Open Users > Create User1 with tenant=tenant1
Add full access role to User1
Logout, log in using "tenant1|User1"
Open Tenants > Create tenant2

AR:
When creating a tenant `Tenant id`  is always equal to `Tenant id` user. Regardless of what the user entered. 
![image](https://user-images.githubusercontent.com/114649487/211293264-4e40d2dd-683d-4834-8a1d-11793c30ba14.png)


Perhaps the `Tenant id` should be filled in when creating a new one **tenant**.

**Comment by KremnevDmitry** [comment]
@rusiaikinat,
### Some notes

For point 1: This is not within the scope of the task. The issue for this bug #1178 

For point 2: It is not entirely correct to give the SystemFullAccess role to a user that belongs to a tenant. Tenants must be created by global administrators who are not tied to tenants.

**Comment by KremnevDmitry** [comment]
### How to use

### Installation: 
The Add-ons section:
![image](https://user-images.githubusercontent.com/75516667/225873752-d95d913f-d56c-497b-8662-6c46f2aa9301.png)

For manual installation, add the following dependencies to your build.gradle:
```
    implementation 'io.jmix.multitenancy:jmix-multitenancy-starter'
    implementation 'io.jmix.multitenancy:jmix-multitenancy-flowui-starter'
```

### How it works:

In the same way as in the Сlassic UI: [link](https://docs.jmix.io/jmix/multitenancy/index.html#how-it-works)

### Managing Tenants:
Tenant administration views:


### Tenant Users:
Same way as Classic UI [[link](https://docs.jmix.ru/jmix/multitenancy/index.html#tenant-users)], but

1. Vaadin `Location` is used instead of UrlRouting.

The location can be received in the view's BeforeEnterEvent:

Example for LoginView:
```
    private Location currentLocation;

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        currentLocation = event.getLocation();
        super.beforeEnter(event);
    }
    
    @Subscribe("login")
    public void onLogin(LoginEvent event) {
        String username = multitenancyFlowuiSupport.getUsernameByLocation(event.getUsername(), currentLocation);

        try {
            loginViewSupport.authenticate(
                    AuthDetails.of(username, event.getPassword())
                            .withLocale(login.getSelectedLocale())
                            .withRememberMe(login.isRememberMe())
            );
        } catch (BadCredentialsException | DisabledException | LockedException | AccessDeniedException e) {
            log.info("Login failed", e);
            event.getSource().setError(true);
        }
    }
```
![login-test](https://user-images.githubusercontent.com/75516667/225881580-0381d1bd-5082-4eae-8fae-cc2b01e5833b.gif)

2. Users can provide the full username including the tenant-id, for example tenant|user.

![login-test2](https://user-images.githubusercontent.com/75516667/225883692-795d3fd2-79f2-4028-82f6-96aefead1ec0.gif)


### Configuring Users:
Points 1-3 same as Classic UI: [link](https://docs.jmix.io/jmix/multitenancy/index.html#configuring-users)
4. `<comboBox id="tenantField" property="tenant" readOnly="true"/>`
5.
```
  @ViewComponent
    private JmixComboBox<String> tenantField;
    
    @Autowired
    private TenantProvider tenantProvider;
    @Autowired
    private MultitenancyFlowuiSupport multitenancyUiSupport;
    
    @Subscribe
    public void onInit(InitEvent event) {
        timeZoneField.setItems(List.of(TimeZone.getAvailableIDs()));
        tenantField.setItems(multitenancyUiSupport.getTenantOptions());
    }
    
    @Subscribe
    public void onInitEntity(InitEntityEvent<User> event) {
        tenantField.setReadOnly(false);
        usernameField.setReadOnly(false);
        passwordField.setVisible(true);
        confirmPasswordField.setVisible(true);
    }

    @Subscribe
    public void onBeforeShow(BeforeShowEvent event) {
        String currentTenantId = tenantProvider.getCurrentUserTenantId();
        if (!currentTenantId.equals(TenantProvider.NO_TENANT)
                && Strings.isNullOrEmpty(tenantField.getValue())) {
            tenantField.setReadOnly(true);
            tenantField.setValue(currentTenantId);
        }
    }
    
    @Subscribe("tenantField")
    public void onTenantFieldComponentValueChange(AbstractField.ComponentValueChangeEvent<JmixComboBox<String>, String> event) {
        usernameField.setValue(
                multitenancyUiSupport.getUsernameByTenant(usernameField.getValue(), event.getValue())
        );
    }
```

6. Vaadin `Location` is used instead of UrlRouting.

The developer must provide the correct _URL query parameter_ in the login view.
```
    @Autowired
    private MultitenancyFlowuiSupport multitenancyFlowuiSupport;
    
    private Location currentLocation;

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        currentLocation = event.getLocation();
        super.beforeEnter(event);
    }
    
    @Subscribe("login")
    public void onLogin(LoginEvent event) {
        String username = multitenancyFlowuiSupport.getUsernameByLocation(event.getUsername(), currentLocation);

        try {
            loginViewSupport.authenticate(
                    AuthDetails.of(username, event.getPassword())
                            .withLocale(login.getSelectedLocale())
                            .withRememberMe(login.isRememberMe())
            );
        } catch (BadCredentialsException | DisabledException | LockedException | AccessDeniedException e) {
            log.info("Login failed", e);
            event.getSource().setError(true);
        }
    }
```

### Configuring Security:
Same as Classc UI: [link](https://docs.jmix.io/jmix/multitenancy/index.html#configuring-security)


### Test project attached: 
[flowui-multitenancy-test-master.zip](https://github.com/jmix-framework/jmix/files/11000602/flowui-multitenancy-test-master.zip)
