### ISSUE TITLE
Unable to use `antMatchers()` in a security configuration extension

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1332]
For example, if you create the following extension in a FlowUI project:
```
@Component
@Qualifier(FlowuiSecurityConfiguration.SECURITY_CONFIGURER_QUALIFIER)
public class MySecurityConfigurer extends AbstractHttpConfigurer<MySecurityConfigurer, HttpSecurity> {

    @Override
    public void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests().antMatchers("/img/**").permitAll();
    }
}
```

you will get `java.lang.IllegalStateException: Can't configure antMatchers after anyRequest` on app start.

**Comment by gorbunkov** [comment]
The goal (provide access to some resource) can be achieved using the recommendation from this [forum topic](https://forum.jmix.io/t/static-resources-problem/2351/10?u=gorbunkov): a separate `SecurityFilterChain` can be created.

As for configuring the HtpSecurity object by providing ant patterns, this will not work. The reason is that Jmix classes like `io.jmix.security.configurer.UiUrlsConfigurer` immediately modify HttpSecurity objects when these configurers are applied (see `io.jmix.security.configurer.UiUrlsConfigurer#setBuilder`). The code from Jmix configurers is execuded when `http.apply(configurer)` is invoked, not when HttpSecurity is being built (`http.build()`). 

We should consider reworking these "standard configurers from Jmix" in #2791 - they probably shouldn't use the `setBuilder()` method.
