### ISSUE TITLE
Duplicate Quartz Job created when changing Job's identity

### ISSUE THREAD

**Issue by BryanYin** [jmix-framework/jmix#1338]
By following `PessimisticLockScheduleAutoConfiguration`, I'm trying to add Quartz job programmatically. Everything works fine after create similar `JobDetail` and `Trigger` beans - new job had been added to Quartz related tables. 

But after I change the job identity in argument of `withIdentity()` method then restart the application, it added again the same job:
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/25950822/211828736-853b4bfd-defa-43e2-8373-31049e9fe1fa.png">

You can see that the `source` and `Trigger description` are messed up for the 3 duplicated rows.

ER:
After change job identity, only 1 job added.

AR:
Duplicate Jobs added.

**Comment by gorbunkov** [comment]
Why do you think it's working wrong? It's legal to have multiple jobs of the same type, but with different schedule.
As for changing job id in the class, then I'm afraid Spring doesn't know that you've changed the id of some existing job. For Spring and Quartz it's non-existing job that needs to be created. It's like you came to the **Quartz jobs** screen and created a new job with the same class, but different id manually.

**Comment by BryanYin** [comment]
Hi @gorbunkov,

I just double checked the source code, `JobModel` is not persistence entity...

**Comment by gorbunkov** [comment]
@BryanYin 

Inside the Jmix Quartz add-on there is a setting that stores quartz jobs in the database:

```
spring.quartz.job-store-type=jdbc
```

You see jobs with old IDs because Spring created them while creating corresponding beans. After that it's not Spring responsibility to remove them when you decided to change the id. So you'll have to delete these jobs somehow on the project level.

If you don't need jobs to be stored in the database you may define the following application property in your application:

```
spring.quartz.job-store-type=memory
```

In this case all the jobs will be recreated on application server start, but all jobs created manually in the Jobs screen will be removed because there are no Spring beans for them. Maybe this solution will work for you.

**Comment by BryanYin** [comment]
Thanks @gorbunkov.
Indeed, for my case, use memory as job storage is enough for now. 

Also, you have already anticipated the problem:
>but all jobs created manually in the Jobs screen will be removed

The same issue may still happen in various Jmix applications. 

Do you think we can add below ability to Quartz add-on to completely resolve this issue?
> you'll have to delete these jobs somehow on the project level.

**Comment by gorbunkov** [comment]
I'm not sure that it's a major problem. This behavior will be the same in any pure Spring + Quartz application. Right now we can't get information that "this job should be removed because its id has been changed in the code" from anywhere. I'll keep the issue opened.
