### ISSUE TITLE
Calendar injection has incorrect generic type

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1410]
### Description
See forum discussion: [topic](https://forum.jmix.ru/t/calendareventmoveevent/861)

It seems that injection of `Calendar` and its events has incorrect generic type.

For instance, injection of calendar with `Task` data container:
```
@Autowired
private Calendar<Task> tasksCalendar;
```
But it should have one of date types instead of entity. So we have wrong type in events and even in methods that take a date parameter:

![image](https://user-images.githubusercontent.com/22093943/216907410-ee8664ef-c972-49af-9c65-3996d7e55e85.png)

**Comment by KremnevDmitry** [comment]
Probably it's Jmix Studio issue
Now everything works correctly:
![image](https://user-images.githubusercontent.com/75516667/221542532-0e278ce1-2095-4902-b90e-0914d9379a38.png)
![image](https://user-images.githubusercontent.com/75516667/221542586-dc79229b-7679-45c4-8f17-41af3cf5253f.png)



Can't reproduce on:
Jmix version: 1.0.0
Jmix Studio plugin version: 1.5.SNAPSHOT-223
IntelliJ version: IntelliJ IDEA 2022.3.1 (Community Edition)

**Comment by KremnevDmitry** [comment]
Reproduced on Jmix Framework 1.4.4.
Can't reproduced on Jmix Framework 1.0.0.

Code difference in Studio MetaAnnotations (dataContainer property description):
1.4.4: ` @StudioProperty(name = "dataContainer", type = PropertyType.COLLECTION_DATACONTAINER_REF, typeParameter = "V")`
1.0.0: `@StudioProperty(name = "dataContainer", type = PropertyType.DATACONTAINER_REF)`

So, not a Framework Issue. Changes were made due to: https://github.com/jmix-projects/jmix-ui/issues/654
Created Studio Issue: [JST-3691](https://youtrack.haulmont.com/issue/JST-3691) Wrong generic datatype for Calendar component
