### ISSUE TITLE
Webdav document can't be opened via LibreOffice 7.3+

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#1559]
Check https://wiki.documentfoundation.org/ReleaseNotes/7.3 - Webdav support has been reworked in LibreOffice 7.3.

**Comment by syncro** [comment]
WebDAV via HTTPS in LibreOffice doesn't work with self-signed certificates. To deail with this trusted certificates must be used or for developer purposes it's possible also to create own Root Certificate and sign server's certificate with it.
The easiest way I found is to use mkcert tool.

Install mkcert from the following repo:

https://github.com/FiloSottile/mkcert

You can build it from source and copy binary to /usr/local/bin. 

Now you can generate and install root certificate

`mkcert -install`

Prepare project keystore
Open terminal program or IntelliJ’s panel

Navigate to project root folder if needed, with the following command: 

`cd ~/projects/testjmixwebdav`

Create keystore folder in resources and go into:

```
mkdir src/main/resources/com/company/testjmixwebdav/keystore -p
cd src/main/resources/com/company/testjmixwebdav/keystore
```

Create signed certificates for your development servers with the same tool:

`mkcert localhost 127.0.0.1 ::1`

In case you want your server to be accessible for other networking hosts like devices or virtual machines you should use your real ip address instead of localhost and 127.0.0.1. ipconfig or ifconfig command line commands will probably give you more info on your computer ip addresses.

For my input mkcert created two files: 
localhost+2.pem 
localhost+2-key.pem 

Create JKS keystore from certs
To add them to .jks keystore suitable for jmix embedded server we should convert the certificate to p12 format. You can use 123456 for passwords for everytime when asked for input.

`openssl pkcs12 -export -in localhost+2.pem -inkey localhost+2-key.pem -out localhost+2.p12 -name "localhost"`

Then we can create .jks keystore file with certs for our project:

`keytool -importkeystore -srckeystore localhost+2.p12 -srcstoretype pkcs12 -destkeystore localhost.jks `

Configure your project for HTTPS
Ensure you have the HTTPS configuration in your project’s application.properties file:

```
server.ssl.enabled=true
server.ssl.key-store-type = JKS
server.ssl.key-store = classpath:com/company/testjmixwebdav/keystore/localhost.jks
server.ssl.key-store-password = 123456
server.ssl.key-alias = localhost
server.port = 8443
```

Now you can restart your project and reopen https://localhost:8443 in browser. It should not show the warning site connection icon anymore and LibreOffice will open and save documents from this host
