### ISSUE TITLE
"Could not navigate" error while opening entity detail view in Flow UI

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#1603]
The error "Could not navigate ..." occurs while opening entity detail view (editor screen) if entity has `String` id property and id contains symbol `/`.

The problem can be reproduced in [jmix-flowui-sandbox](https://github.com/daring2/jmix-flowui-sandbox) project:
1. Start the application and open the "Test entities" screen.
2. Create a new entity with id 'abc/def'.
3. Try to open entity editor screen.

Result: The error `Could not navigate to 'testEntities/abc/def' occurs.

**Comment by glebfox** [comment]
We don't recommend using special URL character in Id as it leads to conflicts. In this particular case, even if we encode `/` as `%2F` and then decode backward it will conflict with actual value `%2F` as it will be incorrectly decoded to `/` and so on. To prevent these conflicts, the only restricted character in String Id is `/`, because it handled by `com.vaadin.flow.router.Location` as path separator.
