### ISSUE TITLE
CheckBox in forms duplicates its icon

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1604]
### Description
See forum [discussion](https://forum.jmix.io/t/double-icon-at-checkbox/2818).

### Steps to reproduce
1. Add the following checkBox to form:
```
<checkBox id="warn" caption="Warning" icon="WARNING" contextHelpText="some helpful text"/>
```
**AR**
![image](https://user-images.githubusercontent.com/22093943/232071686-5be87e40-98a8-4e64-857c-72784c5c4a14.png)

**Comment by KremnevDmitry** [comment]
Probably the problem is:
com.vaadin.client.ui.checkbox.CheckBoxConnector#onStateChanged:100
![image](https://user-images.githubusercontent.com/75516667/234238331-dbb4a082-676d-41c2-a0c4-f405af117754.png)

Probably solution:
Implement setIcon such as `com.vaadin.client.VCaption#setCaptionText(com.google.gwt.user.client.ui.HasHTML, com.vaadin.shared.AbstractComponentState)`

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5134-223
IntelliJ version: IntelliJ IDEA 2022.3.3 (Ultimate Edition)
