### ISSUE TITLE
Required Indicator is blue by default

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#2200]
Jmix 2.0.1

Required Indicator is blue by default for the empty required field.
It becomes red when related field gains and loses focus.

![image](https://github.com/jmix-framework/jmix/assets/32579132/b247dd10-e297-44a6-9394-971b62ce4b25)

**Comment by glebfox** [comment]
@Gavrilov-Ivan could you please provide exact steps to reproduce?

**Comment by Gavrilov-Ivan** [comment]
1. There is an entity with required properties (Employee, Work Type).
2. DetailView for this entity is opened via ViewNavigators on button click.

As example you can check this demo project - https://github.com/jmix-framework/jmix-commercial-addons-demo-2
Perform first two steps from scenario: run, login as alice/1, go to _Application_ -> _Workspace requests_ and click _Start workspace preparation process_ button. There will be View the screenshot above has been taken from.

**Comment by KremnevDmitry** [comment]
Bug can't be reproduced:
![image](https://github.com/jmix-framework/jmix/assets/75516667/f8a7ca94-26ce-4597-967f-70b133d63a15)

**Comment by KremnevDmitry** [comment]
This behavior is caused by the synchronization of component property values on the server and client sides: https://github.com/vaadin/flow/issues/3496

Vaadin use a workaround:
![image](https://github.com/jmix-framework/jmix/assets/75516667/2d1210ef-fea3-4f4d-adb9-bc809dd819ab)

Our databinding sets the `invalid` property value to `true` for server-side component before the client-side component is event created.

As a result - the problem described above by @Gavrilov-Ivan

**Comment by glebfox** [comment]
@KremnevDmitry perhaps we can defer first changing if `invalid` property until a component is attached (AttachEvent)?

**Comment by KremnevDmitry** [comment]
> @KremnevDmitry perhaps we can defer first changing if `invalid` property until a component is attached (AttachEvent)?

I'll research the implementation

**Comment by KremnevDmitry** [comment]
Related to Vaadin issue: https://github.com/vaadin/flow-components/issues/5616
