### ISSUE TITLE
Make DataGrid columns resizable by default

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2275]
Also, set `columnReorderingAllowed="true'`.
Also, check existing platform views and add these settings (e.g. [forum](https://forum.jmix.io/t/flowui-datagrid-columns-should-be-resizeable-per-default/3669)).

---

Add corresponding settings to the list view template and set `true` by default.

**Comment by KremnevDmitry** [comment]
New attribute `resizable` has been added to the `<columns/>` tag.

How you can use:
![image](https://github.com/jmix-framework/jmix/assets/75516667/955731a2-f761-4c2c-b8bc-538701c4a925)

Instead of:
![image](https://github.com/jmix-framework/jmix/assets/75516667/3396d60c-1d4c-4dc0-884e-11a7beb0d234)

**Comment by KremnevDmitry** [comment]
Add-ons:

- [ ] AppSettings
- [ ] Audit
- [ ] Datatools
- [ ] Email
- [ ] FlowUI
- [ ] Multitenancy
- [ ] Quartz
- [ ] Reports
- [ ] Security
- [ ] BPM
- [ ] BusinessCalendar
- [ ] Notifications

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5673-231
IntelliJ version: IntelliJ IDEA 2023.2.2 (Ultimate Edition)
verified
