### ISSUE TITLE
Unique constraint violation is not handled correctly when using latest MS SQLServer

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2324]
- Start SQLServer, for example in docker: `docker run --cap-add SYS_PTRACE -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=saPass_1' -p 1433:1433 --name azuresqledge -d mcr.microsoft.com/azure-sql-edge`
- Open https://github.com/jmix-framework/jmix-onboarding-2 project
- Change database type to MS SQLServer 2012+, set `sa` / `saPass_1` credentials
- Run the app, create new Department with `Finance` name

ER:
Notification "A department with the same name already exists"

AR:
Unexpected error
SQLServerException: Violation of UNIQUE KEY constraint 'IDX_DEPARTMENT_UNQ_NAME'. Cannot insert duplicate key in object 'dbo.DEPARTMENT'. The duplicate key value is (Finance).

See also [forum topic](https://forum.jmix.io/t/unhandled-sqlserverexception-with-unique-attribute/3724).

**Comment by knstvk** [comment]
To devs: 
setting the `jmix.data.unique-constraint-violation-pattern = Violation of UNIQUE KEY constraint '(.+?)'` property solves the problem on project level. Perhaps we should add this pattern to `SqlServerDbmsFeatures#getUniqueConstraintViolationPattern` using `|`.

To QA: 
test on several different versions of SQLServer.

**Comment by KartnDev** [comment]
# Issue:

## Whats happen

* Right now for for SQL Server we have follow expression: `with unique index '(.+)'`
* We need to catch 
`"SQLServerException: Violation of UNIQUE KEY constraint 'IDX_DEPARTMENT_UNQ_NAME'. Cannot insert duplicate key in object 'dbo.DEPARTMENT'. The duplicate key value is (Marketing)."`

## My (God bless ChatGPT and regex online) solution
* **Do not** catch this phrase: `Violation of UNIQUE KEY constraint '(.+?)'`
* Instead of it i propose to choose this one `The duplicate key value is \((\S+)\)\.?` (End of error message)
* If concate both variants: `(The duplicate key value is \((\S+)\)\.?|with unique index '(.+)')` 
   by rule `(A|B)`

## Tests:
![image](https://github.com/jmix-framework/jmix/assets/43281522/05dd9657-d559-41d1-aa5c-d2c8af7f458a)
![image](https://github.com/jmix-framework/jmix/assets/43281522/c6330df0-d96f-4209-b80c-682b9774725a)
![image](https://github.com/jmix-framework/jmix/assets/43281522/a8af912c-2687-4793-9b39-f2db3325c8ff)
![image](https://github.com/jmix-framework/jmix/assets/43281522/e7df6011-5959-4f4c-a413-dfb7ee984b20)

### Error message was:
![image](https://github.com/jmix-framework/jmix/assets/43281522/a45be68e-d723-46f6-94f6-04965ab36def)

# OR else add space sensitive

![image](https://github.com/jmix-framework/jmix/assets/43281522/8c729fb5-f96a-4190-b2f1-a16ba6fd7fd0)

And then we can use instead similar expression:
(Violation of UNIQUE KEY constraint '(?!\s)(.+?)'\.?|with unique index '(.+)')

**Comment by KartnDev** [comment]
## UPD **(A|B)** => **A|B** regex to omit unwanted group inside regex
UPD: root(first) group `(The duplicate key value is \((\S+)\)\.?|with unique index '(.+)')` should be omitted to prevent break on constaint messages => `The duplicate key value is \((\S+)\)\.?|with unique index '(.+)'`
