### ISSUE TITLE
Sorting issue on WebDAV documents view

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2396]
1. Create several WebDAV documents
2. Sort by last modified date: 
<img width="958" alt="изображение" src="https://github.com/jmix-framework/jmix/assets/38808384/087cafb1-d691-47af-9c24-b91bb30032e0">
3. Click on v1 of middle document and add new version in dialog
4. Click Refresh: documents sorted correctly
5. Click "<-" in breadcrums line
 
  **ER:** documents sorted correctly
  **AR:** documents sorted randomly
 
<img width="958" alt="изображение" src="https://github.com/jmix-framework/jmix/assets/38808384/86fec754-ba89-47ed-ba6e-18a8a8f14650">

**Comment by fractal3000** [comment]
1. Open dialog with WebDAV files.
2. Create several documents.
3. Try to sort documents by "name" or by "lock state" or by "versioning" column. (May be this problem is also actual for the "Last modified by" field)
ER: Sorting is performed
AR: Sorting is not performed

1. Open dialog with WebDAV files.
2. Create document.
3. Open "Manage versions" dialog
4. Add several versions with different file names
5. Try to sort version items by "Version", "Name" column(may be by "Author" column too)
ER: Sorting is performed
AR: Sorting is not performed

**Comment by fractal3000** [comment]
For release 3.0 is implemented in "c52af012" commit in "master" branch.

**Comment by rusiaikinat** [comment]
Reopened
The table with values does not take up the entire screen

![image](https://github.com/jmix-framework/jmix/assets/114649487/2589666b-a932-45a1-8602-bd78fcdca99d)

**Comment by rusiaikinat** [comment]
1. Sorting : It works partially
![image](https://github.com/jmix-framework/jmix/assets/114649487/fea2ef10-bda9-4f48-8968-bf76e33c83ff)

2. Sorting document version : It works 

3. Sorting after search : See point 1

4. Search : It works partially
![image](https://github.com/jmix-framework/jmix/assets/114649487/cff45a43-a323-4ea1-b140-69fbd686dc65)

5. Saving filter: It works

**Comment by fractal3000** [comment]
Reverted from release 2.1

**Comment by fractal3000** [comment]
Reverted from release 2.1

**Comment by rusiaikinat** [comment]
Documents uploaded earlier are not sorted correctly
![image](https://github.com/jmix-framework/jmix/assets/114649487/73f8865e-39e8-4346-98c9-29998278a6aa)

list and order of text files
![image](https://github.com/jmix-framework/jmix/assets/114649487/f03a5d88-9c35-4325-a5ea-0fa0c52e30ee)

**Comment by Gavrilov-Ivan** [comment]
As mentioned before there is a known issue with sorting by file name - it's impossible to fix now and requires additional research and rework.
Are there any other issues besides this one? Sorting by another columns?
