### ISSUE TITLE
Classic UI. Can't peek abbreviated column text-value in lookup mode

### ISSUE THREAD

**Issue by Flamesson** [jmix-framework/jmix#2417]
Hello

### The problem:
A text value display of a column in Jmix Table can be limited by "maxTextLength" property. And user will be able to view full text value. But it works not always. 

In case you open a browse-screen in browse-mode (not for picking values) there will be an opportunity to check full text. 

In case you open a browse-screen in lookup-mode (to pickup value, for example, to a field) there won't be any opportunity to check full text. 

### Steps to reproduce:
* Launch application.
* Open the application in browser.
* Cities browser will be opened automatically in browser-mode. Click on name cell of the single existing row. You will see a popup with full value.
<img width="1512" alt="Cities browser in browse-mode" src="https://github.com/jmix-framework/jmix/assets/51899225/19142da9-57e8-4834-a5d8-1d0a9e2802cf">

* Open officies browse screen (Offices in menu).
* Open the single existing office in editor.
* Click on button to pickup a city for the office. Cities browser will be opened in lookup-mode. Click on name cell of the single existing row. You won't see a popup with full value.
<img width="1512" alt="Cities browser in lookup-mode" src="https://github.com/jmix-framework/jmix/assets/51899225/26b1d192-bacb-456e-a716-2a64fea60918">

![image](https://github.com/jmix-framework/jmix/assets/51899225/1061d957-dbc5-48ee-bc9e-e881ef7bca47)

**Comment by glebfox** [comment]
It appears to be intentional. When `LookupSelectHandler` is set, the `removeAllClickListeners()` method is called. This is needed because `TableCellClickListener` which is used to add `AbbreviatedCellClickListener` handles clicks on the whole table cell and can prevent correct work of `LookupSelectHandler`.

`removeAllClickListeners()` is a `protected` method and can be changed on project level.
