### ISSUE TITLE
Reports code snippets

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#2440]
Create code snippets:

1. Running a report using a report code
2. Running a report using a report entity

**Comment by knstvk** [comment]
Remove examples from code snippet docs.
They are not needed because the whole point of the snippet is to generate code identical to the example.
And they take up too much space, see the screencast:
![screencast 2023-11-20 16-28-24](https://github.com/jmix-framework/jmix/assets/5513878/8220f2ba-384a-4006-8442-78650dac855c)
