### ISSUE TITLE
Support clickShortcut attribute in XML

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2645]
### Feature Description

`ClickNotifier` components have `ClickNotifier#addClickShortcut` that adds a shortcut which 'clicks' the Component. Similar to actions' `shortcutCombination` attribute, we can support `clickShortcut` for corresponding UI components.

**Comment by natfirst** [comment]
Full description required

**Comment by KremnevDmitry** [comment]
The goal of the issue was to support click shortcuts for components that implement `ClickNotifier` interface.
This support has been added for all components except the `button` and its inheritors.

The `button` implements `HasShortcutCombination` interface that provides the same functionality as the {@link ClickNotifier#addClickShortcut(Key, KeyModifier...)}.
The only difference is that a `shortcutCombination` can be assigned to an action. Also, the `shortcutCombination` is an API that is maintained by the Jmix team, as opposed to the `clickShortcut` that is maintained by the Vaadin.

Also, the `shortcutCombination` determines the vision scope of the shortcut, in contrast to the `clickShortcut`, where the scope is defined globally.

Thus, `ShortcutCombination` is a more advanced API of `clickShortcut`. The decision was made not to add appropriate support for `button` components and their inheritors.
