### ISSUE TITLE
Logging out is preceded by a message about unsaved data

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2692]
### Environment

Jmix version: 2.1.999-SNAPSHOT (last version 2.1.1)
Jmix Studio plugin version: 2.1.SNAPSHOT5908-233
IntelliJ version: IntelliJ IDEA 2023.3.2 (Ultimate Edition)

### Bug Description
there is no changed data on the screen, a message about the changed data appears before logout

### Steps To Reproduce
Open users view
Open user edit view 
Cancel
Logout

### Current Behavior
![image](https://github.com/jmix-framework/jmix/assets/114649487/4b449e59-d9c4-4fcd-8bfa-629320f0c882)

### Expected Behavior
There should be no message about the changed data

**Comment by glebfox** [comment]
Also, see related problem: https://forum.jmix.io/t/canceled-logout-from-detail-view-causes-unresponsive-screen/4180/3

**Comment by glebfox** [comment]
**Case 1:**

- Open users list view
- Open user detail view
- **Cancel**
- **Refresh/Close** browser tab

**Prev result:**

Browse's default notification is shown about closing tab

**New result:**

No notification is shown

**Case 2:**

- Open users list view
- Open user **detail** view
- **Logout**

**Prev result:**

Browse's default notification is shown about closing tab. Because logout happens anyway, even if a user stops browser tab closing, the app is broken.

**New result:**

No notification is shown and user logouts even if a detail view has unsaved changes. 

**Note:** `LogoutAction` should trigger close checks of currently opened view, this is topic a of a separate issue: https://github.com/jmix-framework/jmix/issues/2749
