### ISSUE TITLE
Studio doesn't provide an ability to generate selection listener

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#2730]
Handler list for DataGrid in Studio UI doesn't contain SelectionEvent. But it is possible to add selection listener in code manually.
![image](https://github.com/jmix-framework/jmix/assets/50058889/36cbb3a0-e04b-45c7-a53b-11054b99b740)

```
someEntitiesDataGrid.addSelectionListener(new SelectionListener<Grid<SomeEntity>, SomeEntity>() {
    @Override
    public void selectionChange(SelectionEvent<Grid<SomeEntity>, SomeEntity> event) {
        
    }
});
```

**Comment by KremnevDmitry** [comment]
Adding the `SelectionListener` doesn't work in both studio and framework. This occurs because the method doesn't fit the standard definition of a method signature for a subscribe-method. A base subscribe-method has only 1 parameter, which implements `eventObject`.

For example:
```java
    @Subscribe("usersDataGrid")
    public void onDataGridSelect(SelectionEvent<DataGrid<User>, User> event) {
        // do nothing
    }
```

`com.vaadin.flow.data.selection.SelectionEvent` doesn't implements `eventObject`, so the method can't be resolved.

The `SelectionEvent` has two inheritors, which are extends `eventObject`: 

1. `com.vaadin.flow.data.selection.MultiSelectionEvent`
2. `com.vaadin.flow.data.selection.SingleSelectionEvent`

However, for these **particular** events there are no methods to add. It must be added with `io.jmix.flowui.component.grid.DataGrid#addSelectionListener`.

Thus, the only solution to this problem is to implement owr own `SelectionEvent` interface.

To implement **Jmix DataGrid selection events**, we need to override the native Vaadin `SelectionModel` for the DataGrid in order to fire the jmix events.

Thus, the problem ca't be solved right now. This will be fixed in the context of the implementation of the **new Jmix DataGrid selection model**.
