### ISSUE TITLE
Value of fts filter isn't stored by 'Save with values' action

### ISSUE THREAD

**Issue by maistrenkoIulia** [jmix-framework/jmix#308]
relates to https://github.com/haulmont/jmix-search/issues/51

Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3071-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: 
entity browser>filter>add search condition>create full-text filter, set value
Save with value>set name
Reopen browser>select created filter
ER: value should be stored
AR: no value for fts condition
![image](https://user-images.githubusercontent.com/66992566/122555721-b1db5c80-d04b-11eb-9735-552d7b3b7493.png)

**Comment by syncro** [comment]
As of versions 1.5.5 and above this bug is not reproducable. Filter values are restored properly when previously saved configuration is selected.
![380_savedfilter](https://github.com/jmix-framework/jmix/assets/195749/f98ef669-4d53-4b5d-b315-c85dde63aabb)
![380_savedfilter_v2](https://github.com/jmix-framework/jmix/assets/195749/d920bd00-07d1-49f5-af9f-fcf0bf8d6e99)
