### ISSUE TITLE
Use CodeEditor component in report template editor

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3085]
Change the `ReportTemplateDetailView` design in the Reports add-on:
- Change `TextArea` with `CodeEditor`
- Added `FullScreen` button

**Comment by rusiaikinat** [comment]
Reopened

1. The `Full screen` button is missing a field, It may be worth hiding `Full screen` if template editing is not available
![image](https://github.com/jmix-framework/jmix/assets/114649487/5bcab194-27c9-4ee1-a42a-a624abcfbddc)

3. For consistency, change the `customDefinitionField` (TextArea) field type to CodeEditor
4. If possible, then do line wrapping in `templateFileEditor` Full screen view

**Comment by syncro** [comment]
1. fullscreen display is fixed with https://github.com/jmix-framework/jmix/issues/3085 but new code will be dependant on it
2. will be done withing current issue
3. Code editor currently doesn't support text wrapping (create issue for that: https://github.com/jmix-framework/jmix/issues/3085). So this should be moved in separate issue
