### ISSUE TITLE
Open a file in WebDAV document cause message 'This site can't be reached'

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3235]
### Environment

Jmix version: 2.2.3

### Bug Description

After clicking the Open button, a web page opens with message 'This site can't be reached'

### Steps To Reproduce

![image](https://github.com/jmix-framework/jmix/assets/158277660/5b51c16b-43d9-47c7-9274-802171f088a1)

1. Add WebDAV addon
2. Open WebDAV > WebDAV documents
3. Upload a file
4. Click to file version sign (pop-up opened)
5. Click 'Open' button

### Current Behavior

New web page opens with message 'This site can't be reached'

![image](https://github.com/jmix-framework/jmix/assets/158277660/2c9f91da-3cf0-4346-b3e8-a71089815ddc)

### Expected Behavior

A file is opend.

### Sample Project

[jmix-flowui-smoke-test](https://github.com/jmix-projects/jmix-flowui-smoke-test)

**Comment by Gavrilov-Ivan** [comment]
Looks like not a bug.

WebDAV generates links using url prefix (https://docs.jmix.io/jmix/webdav/webdav-properties.html#jmix.webdav.url-prefix) and the default one is https://localhost:8443/webdav (because https is required for most functionality).

So you should either configure https in your project (so application is running on https://localhost:8443) or set `jmix.webdav.url-prefix=http://localhost:8080/webdav` if you don't need https for test case.

**Comment by SergeiAksenov2** [comment]
Tested on Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6389-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6385-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

Uloaded docx file is opend in test applications  - Ok.
