### ISSUE TITLE
Fix ListMenu component focus styles

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3541]
### Environment

Jmix version: 2.3.1

### Bug Description

`listMenu` components has 

### Steps To Reproduce

Use the <kbd>Tab</kbd> key to navigate through different menu items

### Current Behavior

1. Focus-ring for root menus is cut off on the right and has no padding on the left 

<img width="269" alt="Screenshot 2024-08-02 at 22 56 44" src="https://github.com/user-attachments/assets/15c2a9b5-c9dc-4af6-aa2b-e5f0e25a5ab6">

2. Focus-ring for menu items is cut off on the right and ignores theme settings like color and border radius

<img width="263" alt="Screenshot 2024-08-02 at 22 57 48" src="https://github.com/user-attachments/assets/82fd60ce-073d-46b5-8334-6bcaa82d3000">

3. Focus-ring for **selected** menu items is cut off on the right has incorrect color

<img width="263" alt="Screenshot 2024-08-02 at 23 01 43" src="https://github.com/user-attachments/assets/7f420c57-8c9c-418d-b68c-607bd09b96ff">

### Expected Behavior

Fix it?

**Comment by Flaurite** [comment]
After investigation without changing sizes we can only fix color styles. So we have the following:
1) Will be fixed in 2.4
2) Color and border radius will be fixed within current issue. Cutting of will be fixed in 2.4
3) Color will be fixed within current issue. Cutting of will be fixed in 2.4

The issue for 2.4: https://github.com/jmix-framework/jmix/issues/3589

### How to test
1. Copy this code snippet to `styles.css` file in your project:

<details>
<summary>Code snippet</summary>

```
html {
    --lumo-border-radius: calc(var(--lumo-size-m) / 2);
    --lumo-size-xl: 4rem;
    --lumo-size-l: 3rem;
    --lumo-size-m: 2.5rem;
    --lumo-size-s: 2rem;
    --lumo-size-xs: 1.75rem;
    --lumo-space-xl: 2.5rem;
    --lumo-space-l: 1.75rem;
    --lumo-space-m: 1.125rem;
    --lumo-space-s: 0.75rem;
    --lumo-space-xs: 0.375rem;
    --lumo-primary-text-color: rgb(114, 22, 243);
    --lumo-primary-color-50pct: rgba(114, 22, 243, 0.5);
    --lumo-primary-color-10pct: rgba(114, 22, 243, 0.1);
    --lumo-error-text-color: rgb(255, 56, 103);
    --lumo-error-color-50pct: rgba(255, 56, 103, 0.5);
    --lumo-error-color-10pct: rgba(255, 56, 103, 0.1);
    --lumo-success-text-color: rgb(20, 184, 143);
    --lumo-success-color-50pct: rgba(20, 184, 143, 0.5);
    --lumo-success-color-10pct: rgba(20, 184, 143, 0.1);
    --lumo-primary-color: hsl(265, 90%, 52%);
    --lumo-error-color: hsl(346, 100%, 61%);
    --lumo-success-color: hsl(165, 80%, 40%);
    --lumo-header-text-color: hsl(285, 35%, 15%);
    --lumo-body-text-color: hsla(285, 40%, 16%, 0.94);
    --lumo-secondary-text-color: hsla(285, 42%, 18%, 0.72);
    --lumo-tertiary-text-color: hsla(285, 45%, 20%, 0.5);
    --lumo-disabled-text-color: hsla(285, 50%, 22%, 0.26);
}
```

</details>

2. Check that border and color of outline is applied.
3. Select menu item by enter. Check that color of outline is still applied.
