### ISSUE TITLE
Add URL State Persistence for Calendar Add-on

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#3710]
**Description:**

Currently, the Calendar Add-on allows users to switch between display modes (e.g., day, week, month) and navigate through dates, but these changes are not reflected in the URL. This limits the ability to bookmark, share, or return to a specific calendar view easily. Even more importantly it breaks the flow of back button of the browser

**Proposed Solution:**

We propose enhancing the Calendar Add-on by adding URL state persistence for the selected display mode and date, similar to existing implementations for `GenericFilter` and `Pagination` using the `URLQueryParametersFacet`.

From a users PoV a solution would involve the Calendar Add-on providing a default implementation that automatically covers all state changes for the display mode and selected date. The goal is for developers to easily configure URL query parameters for the calendar in a similar fashion to `GenericFilter` and `Pagination`:

```xml
<facets>
    <urlQueryParameters id="urlQueryParameters">
        <pagination component="pagination"/>
        <genericFilter component="genericFilter"/>
        <calendar:display component="myCalendar"/>
    </urlQueryParameters>
</facets>
```

which would result in a URL something along those lines: `localhost:8080/petclinic/visits?calendarDisplayMode=dayGridMonth&date=2024-10-06`

**Comment by Flaurite** [comment]
## Changes

### In Flowui
Now `UrlQueryParametersFacet` supports binders from other add-ons. To create custom binder for component you need:

1) Implement `UrlQueryParametersBinderProvider` interface
2) Create binder class that binds URL parameters and state of the component
3) Create your XSD schema in order to specify paramters in XML.

See example: 
 - https://github.com/jmix-framework/jmix/blob/master/jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/PaginationUrlQueryParametersBinder.java
  - https://github.com/jmix-framework/jmix/blob/master/jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/PaginationUrlQueryParametersBinderProvider.java
  
### In Calendar
Now Calendar using `UrlQueryParametersFacet` can update URL state by:
 - calendarDate
 - calendarDisplayMode
 
 Example:
 ```
 <facets>
    <urlQueryParameters>
        <calendar:calendarParameters component="calendar"/>
    </urlQueryParameters>
</facets>
<layout>
    <calendar:calendar id="calendar"
                       height="100%"
                       width="100%">
    </calendar:calendar>
</layout>
 ```
 
 `http://localhost:8080/url-query-parametrs-view?calendarDisplayMode=dayGridMonth&calendarDate=2024-10-09`
  
![image](https://github.com/user-attachments/assets/9ddc3e67-bcfc-4678-956f-20568cd241fd)
