### ISSUE TITLE
AppSettingsEntityView uses Messages instead if MessageBundle

### ISSUE THREAD

**Issue by pbaris** [jmix-framework/jmix#3711]
### Environment

Jmix version: 2.3.3

### Bug Description

Extending AppSettingsEntityView breaks field labels for currentValueLabel and defaultValueLabel.

### Steps To Reproduce

Use studio to extend default AppSettingsEntityView.

### Current Behavior

Extended AppSettingsEntityView breaks currentValueLabel and defaultValueLabel.

![image](https://github.com/user-attachments/assets/c67de804-93f9-4056-8f5c-244c3fe1ec7b)

I have to manually add the entries in messages_en.properties, in order to work

```
gr.netmechanics.view.extappsettingsentity/currentValueLabel=Current value
gr.netmechanics.view.extappsettingsentity/defaultValueLabel=Default value
```
![image](https://github.com/user-attachments/assets/d3709354-2109-4bb5-8437-d78ff7d4a62c)

### Expected Behavior

After extending the view, the labels should work without adding manually the entries in messages_en.properties.

**Comment by glebfox** [comment]
When extending/overriding a view, manual changes are required anyway because, when extending/overriding a view and the `MessageBundle` is used in this parent view controller, it's required that the `messageGroup` of the new child view be set to the same value as that of the parent view. Otherwise, messages will be loaded with the `messageGroup` from a new view, and cannot be found. For example:

```java
@Route(value = "pslock/pessimistic-locks", layout = MainView.class)
@ViewController("pslock_LockInfo.list")
@ViewDescriptor("ts-pessimistic-lock-list-view.xml")
public class TsPessimisticLockListView extends PessimisticLockListView {

    @Override
    public void onInit(InitEvent event) {
        messageBundle.setMessageGroup("io.jmix.pessimisticlockflowui.view.pessimisticlock");
        super.onInit(event);
    }
}
```

I agree that coping messages less convenient that simply changing `messageGroup`, so in the upcoming Jmix v2.4 `AppSettingsEntityView` will use `MessageBundle` instead of `Messages`.
