### ISSUE TITLE
Optimistic lock occurs in case of saving a new entity using delegate

### ISSUE THREAD

**Issue by m-orlova** [jmix-framework/jmix#3961]
### Environment

Jmix version: 2.4.1

### Bug Description

It is not possible to save a new entity after changes using save delegate and `getEditedEntity()` if the unique constraint violates. In this case, an optimistic lock exception is thrown however the entity stays as new and is not saved to the database. 
But entity saving works if use `saveContext.getEntitiesToSave().get(User.class, getEditedEntity().getId())` to get an entity.

Example:
```
   @Install(target = Target.DATA_CONTEXT)
    protected Set<Object> saveDelegate(final SaveContext saveContext) {
        //does not work
        userService.saveUser(getEditedEntity());

        //works
        //userService.saveUser(saveContext.getEntitiesToSave().get(User.class, getEditedEntity().getId()));
        return Set.of();
    }
```

### Steps To Reproduce

1. Open Users from menu
2. Try to create a user with the `admin` username
   ER=AR
![image](https://github.com/user-attachments/assets/218fc0e6-2aca-44cd-abd2-eb9d66ccd6ff)

3. Change a username to non-existing value and try to save

### Current Behavior
New user is not saved because of optimistic lock exception.
 ![image](https://github.com/user-attachments/assets/c3b4005b-718b-4d5e-9b1c-c9bb8c53dfde)

### Expected Behavior
A new entity is saved to the database.

### Sample Project
[newentityoptlock.zip](https://github.com/user-attachments/files/17978534/newentityoptlock.zip)

**Comment by knstvk** [comment]
The problem appears because the entity instance returned from `getEditedEntity()` is modified by the backend during the unsuccessful save - the version is incremented. At the same time, the instance from `saveContext.getEntitiesToSave().get(User.class, getEditedEntity().getId())` is a clone created by `DataContext`, so its changes to do not affect the original edited instance.

The solution is to copy the edited instance and save the copy, the same as DataContext does. For example, define the following bean in your project:
```
package com.company.newentityoptlock.app;

import io.jmix.core.impl.StandardSerialization;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class Copier {

    @Autowired
    private final StandardSerialization serialization;

    public Copier(StandardSerialization serialization) {
        this.serialization = serialization;
    }

    @SuppressWarnings("unchecked")
    public <T> T copy(T source) {
        return (T) serialization.deserialize(serialization.serialize(source));
    }
}
```

And use it in the save delegate:
```
@Autowired
private UserService userService;
@Autowired
private Copier copier;

@Install(target = Target.DATA_CONTEXT)
protected Set<Object> saveDelegate(final SaveContext saveContext) {
    User userCopy = copier.copy(getEditedEntity());
    userService.saveUser(userCopy);
    return Set.of(userCopy);
}
```

In the next feature release we are going to provide an API for making copies in the framework, see #3937.
