### ISSUE TITLE
Add file cleared event to FileStorageUpload

### ISSUE THREAD

**Issue by glebshalyganov** [jmix-framework/jmix#417]
Introduce a new event or reuse the existing AfterValueClearEvent and fire it when an uploaded file is cleared, but the value itself (FileRef) is not changed. For example, it is relevant for MANUAL mode, when calling the `clear()` method clears the file but doesn't produce any events.
See the corresponding [forum discussion](https://forum.jmix.io/t/with-filestorageputmode-manual-no-valuechange-events-are-sent).

**Comment by Flaurite** [comment]
Concerning the case from forum, field does not produce ValueChangeEvent because value is not changed (always were null). To make it works correctly, it is need to set value explicitly  to the field.
`BeforeValueClearEvent` and `AfterValueClearEvent` are always invoked when the user clicks on "Clear" button.
