### ISSUE TITLE
Interval filter conditions look ugly

### ISSUE THREAD

**Issue by glaschenko** [jmix-framework/jmix#436]
![image](https://user-images.githubusercontent.com/17944806/130659466-c2c5c2db-48f0-4e44-937c-b1a4356aa7db.png)

**Comment by glebfox** [comment]
The [columnsCount](https://docs.jmix.io/jmix/ui/vcl/components/filter.html#filter-attribute-columns-count) attribute should be used in case of limited space (e.g. in master-detail screen) in order to provide more space for condition fields. By default `columnsCount` = 3 which is suitable for a standard browser screen.

**Comment by rusiaikinat** [comment]
Jmix 1.5.4
Jmix 1.6.0-M1

Master-detail-screen

https://github.com/jmix-framework/jmix/assets/114649487/ae289863-268d-4335-9e95-265a374542f0
