### ISSUE TITLE
Can't start a JMIX project : Broken Dependency

### ISSUE THREAD

**Issue by DREIZ3R** [jmix-framework/jmix#657]
![image](https://user-images.githubusercontent.com/7696828/161422043-7fea66f4-928a-4787-bab8-898a0da34b15.png)
`Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.webjars.npm:mime-db:1.52.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/webjars/npm/mime-db/1.52.0/mime-db-1.52.0.pom
       - https://global.repo.jmix.io/repository/public/org/webjars/npm/mime-db/1.52.0/mime-db-1.52.0.pom
     Required by:
         project : > io.jmix.bom:jmix-bom:1.1.4 > org.webjars.npm:github-com-artf-grapesjs-preset-newsletter:0.2.20 > org.webjars.npm:juice:4.3.2 > org.webjars.npm:web-resource-inliner:4.3.4 > org.webjars.npm:request:2.88.2 > org.webjars.npm:mime-types:2.1.35
`

**Comment by gorbunkov** [comment]
Clean Jmix projects works fine. The problem seems to be caused by the new version of [mime-types](https://search.maven.org/artifact/org.webjars.npm/mime-types/2.1.35/jar) - it uses the mime-db 1.52.0 but its webjar is not in maven central yet.
This dependency is used, for example,  by GrapesJS and EmailTemplates add-ons

**Comment by DREIZ3R** [comment]
My project has GrapeJS and EmailTemplates. After removing EmailTemplates everything worked. Thank you.

**Comment by knstvk** [comment]
It was a temporary problem with webjar artifacts in Maven central. Now the required version is available, so everything should work.
