### ISSUE TITLE
In extended screens, message packets are not pulled up

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#980]
Jmix version: 1.3.2
Jmix Studio plugin version: 1.4.SNAPSHOT4578-222
IntelliJ version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)

See [topic](https://forum.jmix.ru/t/nasledovanie-ekranov-add-onov-i-pakety-soobshhenij/566).
**Steps**:
1.Create new project.
2. Add addons Audit and Russian Translation.
3. Create an extended screen for Entity Log.
4. Add the created screen to the menu.
5. Run project.
6. Change the language to Russian and log in admin/admin.
7. Open "extented entity log".
**ER**:
The extended screen is translated into Russian.
**AR**:
The screen is not translated, the language packs from the addon are not pulled up.
![Снимок экрана от 2022-08-29 13-42-10](https://user-images.githubusercontent.com/95623805/187183787-03385717-8428-46cd-8074-6a057ba7298a.png)

**Comment by glebfox** [comment]
Basically, not a bug. By default message group is obtained either from the `messageGroup` attribute from XML descriptor or from controller class package. Obviously, when a screen is extended, its message group is changed accordingly. Since we don't have separate `message.properties` files for each screen (as we do for CUBA) we can't import messages from base `message.properties`. The solution is either define the `messageGroup` attribute in the XML descriptor equal to the original screen value or do the same programmatically, e.g.:

```
@UiController("themeSettingsScreen")
@UiDescriptor("ext-theme-settings-screen.xml")
public class ExtThemeSettingsScreen extends ThemeSettingsScreen {

   @Autowire
   private MessageBundle messageBundle;
 
   @Override
   public void onInit(InitEvent event) {
       messageBundle.setMessageGroup("io.jmix.ui.app.themesettings");
       super.onInit(event);
   }
}
```
